name: Cerberus.aic
version: 2.1.1
logs_dir: logs/
wiki_base_url: https://scpfoundation.net

runtime:
  work_period:
    minutes: 10
  deletion_period:
    hours: 6

critical:
  rating: 2.0
  votes: 8
  popularity: 66
  delay:
    days: 1

approval:
  votes: 15
  popularity: 66
  rating: 3.0
  delay:
    weeks: 1

grayzone:
  delay:
    days: 30

in_progress:
  categories:
    - wip
  delay:
    days: 30

deletion:
  categories:
    - sandbox
  branch_tags:
    - филиал:ru

tags:
  deletion: полигон:_к_удалению
  approved: полигон:к_переносу
  tagging: полигон:к_тегованию
  whitemark: полигон:_рейтинг_набран

  exclude_with:
    - структура:_защищено
    - конкурс:перепись
    - конкурс:ремейк
    - событие:переоценка

report:
  thread: 3838453
  title: "Re: Журнал удалений"
  prepend: "Удалено по достижении критического рейтинга:"
  line: |
    * {title} - {rating} ({votes}) / {popularity}% _
      Автор: [[user {author}]] _
      Теги: {tags}

posting:
  title: Системное уведомление
  phrases:
    grayzone: |
      Популярность спустя месяц с момента публикации: {popularity}% от {votes}.
      В соответствии с правилами публикации, раздел "Автору", статья переносится в Удалённые.
    too_long_in_progress: |
      В соответствии с правилами публикации, раздел "Автору", статья переносится в Удалённые.
    deletion:
      common:
        - Критический рейтинг набран, статья будет удалена завтра.
      easter:
        - weight: 0.2
          text: Критический рейтинг набран, статья будет съедена завтра.
        - weight: 0.1
          text: Критический рейтинг набран, статья будет передана в Отдел удалений в течение суток.
        - weight: 0.1
          text: Критический рейтинг набран, статья будет отправлена в пространство между мирами завтра.
        - weight: 0.1
          text: Критический рейтинг набран, статья будет удалена из согласованной нормальности завтра.
        - weight: 0.08
          text: В соответствии с пунктом 1.3.1 Правила публикации автору оценки публикационной состоятельности цифрового контента, утверждённого Протоколом от 03.01.2025 года Административно-модераторским составом, а также в силу достижения порогового значения совокупного коэффициента общественного неодобрения (далее — СКОН), зафиксированного на уровне, признаваемом как «критический», настоящим информируется о запланированном на {next_day} г. акте принудительной цифровой дезактивации упомянутой текстовой единицы посредством удаления, ликвидации и вывода из публичного пространства с последующим внесением в Реестр Контента, Не Подлежащего Восстановлению (РКНПВ).
        - weight: 0.05
          text: Критический рейтинг набран, вы ещё можете удалить статью самостоятельно.
        - weight: 0.01
          text: Критический рейтинг набран, Чорная Клика санкционирует завтрашнее удаление.
