category = [ "sandbox",]
tags = [ "филиал:ru", ]
ignored_tag = "полигон:в_работе"
deletes_tag = "_default:_к_удалению"
time = 86400

[critical]
rate = 2
num = 15

[month]
tag = "полигон:_месяц"
declined_tag = "структура:_отклонено-амс"
num = 15

[approved]
popularity = 66
weeks = 2
num = 15
approved_tag = "полигон:к_переносу"

[approved.tags]
protegano = "событие:протегано"
for_tags = "полигон:к_тегованию"

[post]
title = "Автоматический административный пост"
source = "Критический рейтинг набран, статья будет удалена завтра."

[post.easter_eggs]
egg1 = "Критический рейтинг набран, статья будет съедена завтра."

[log]
id = 3838453
title = "Re: Журнал удалений"
source = "Удалено по достижении критического рейтинга:\n{}"
list_template = "* {title} ([[user {user}]]/{rating})"
